series: Ray Tracers
title: Intermediate Ray Tracer
author:
  name: Brockton Roth
  email:
  github: https://github.com/IGME-RIT
description: Demonstration of a more complex ray tracing algorithm.
language: C++
tags:
  - Graphics
  - Math
extra_resources:
  - title: Ray Tracing With Compute Shaders
    link: https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.1.-Ray-tracing-with-OpenGL-Compute-Shaders-(Part-I)
connections:
  - series: Ray Tracers
    title: Basic Ray Tracer
